import { Team } from "./teamsData";

export const coreData: Team[] = [
  // ── Web Development Team (formerly Technical) ──────────────────────────────
  {
    id: "technical",
    label: "Web Development Team",
    members: [
      {
        id: "tc1",
        name: "Devishi Mathur",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc2",
        name: "Divya Srivastava",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc3",
        name: "Namit Tickoo",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc4",
        name: "Ronit Mahajan",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc5",
        name: "Samya Tiwari",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc6",
        name: "Sarthak Malhotra",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc7",
        name: "Vidhyanshu Kumar",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc8",
        name: "Aakanksha Kumar",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/KaI-Jh9PwEellx79_SeniorCoordinator_Technical%26Webdev_Aakanksha_Kumar.jpg?auto=format,compress,
        github: "",
      },
      {
        id: "tc9",
        name: "Tanish Jain",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/Cm-ZcAPvUPNhkJMK_Senior_Coordinator_Technical_Tanish-1-.jpeg?auto=format,compress,
        github: "https://github.com/TanishJain2006",
      },
      {
        id: "tc10",
        name: "Kavya Choudhary",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc11",
        name: "Kethan Anant",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/Pckfv3lLN4u4Cxig_SC_Editorial_KetanAnant.jpg?auto=format,compress,
        github: "",
      },
      {
        id: "tc12",
        name: "Navya Goel",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/7s5ilhcplZJqIR_r_SeniorCordinator_SocialMedia_NavyaGoel.jpg?auto=format,compress,
        github: "https://github.com/navyvyaaa",
      },
      {
        id: "tc13",
        name: "Arnav Srivastava",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/bvGQO_c-u-ULWfRZ_Joint_Head_Technical_Arnav.jpg?auto=format,compress,
        github: "https://github.com/Arnav808",
      },
      {
        id: "tc14",
        name: "Aparna",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc15",
        name: "Aum Lenka",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc16",
        name: "Shaurya Saxena",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc17",
        name: "Aastha Sood",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc18",
        name: "Disha Bothra",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc19",
        name: "Mukti Dewnani",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc20",
        name: "Shlok Pandey",
        role: "Team Member",
        photo: null,
        github: "",
      },
      {
        id: "tc21",
        name: "Tanishq Bhatnagar",
        role: "Team Member",
        photo: null,
        github: "",
      },
    ],
  },

  // ── Graphic Design Team ───────────────────────────────────────────────────
  {
    id: "graphic-design",
    label: "Graphic Design Team",
    members: [
      {
        id: "gd1",
        name: "Aditi Bharadwaj",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd2",
        name: "Ananya Ghosh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd3",
        name: "Monishka Kanodia",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd4",
        name: "Nandini Khandelwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd5",
        name: "Prakhar Raj",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd6",
        name: "Ruhaani Satija",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd7",
        name: "Soham Prashant More",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd8",
        name: "Ananya Srivastava",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/j2FTkMfbNfUbemco_Head_GraphicDesign_AnanyaSrivastav.png?auto=format,compress,
      },
      {
        id: "gd9",
        name: "Arunika",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/rC-iGpTv1cY8MM9o_Joint_Head_Graphic_Design_Arunika.png?auto=format,compress,
      },
      {
        id: "gd10",
        name: "Mit Parekh",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/Ag6pazrMlJuO7-qJ_Senoir.coordinator_GD_Mit.jpg?auto=format,compress,
      },
      {
        id: "gd11",
        name: "Yuvraaj Dutta",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/6h9SpvAuUnYD60u0_SeniorCoordinator_GraphicDesign_YuuvrajDutta.jpeg?auto=format,compress,
      },
      {
        id: "gd12",
        name: "Sahil",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd13",
        name: "Shivanshi Punj",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd14",
        name: "Vaani Dhiman",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd15",
        name: "Vidhi Makkar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd16",
        name: "Maahi Arora",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd17",
        name: "Pranya Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd18",
        name: "Sailendra Sesha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "gd19",
        name: "Vikram Khambra",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Curations Team ─────────────────────────────────────────────────────────
  {
    id: "curations",
    label: "Curations Team",
    members: [
      {
        id: "cu1",
        name: "Anchal Singh",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "cu2",
        name: "Ankush Bhardwaj",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "cu3",
        name: "Atharv Vijayvergiya",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu4",
        name: "Mishika Sehgal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu5",
        name: "Sanvi Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu6",
        name: "Tejas Kaur",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu7",
        name: "Garvit Sharma",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/274TD5B-9Bt_7uBg_WhatsAppImage2026-08-04at23.38.54.jpeg?auto=format,compress,
      },
      {
        id: "cu8",
        name: "Kanishk Punjabi",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/A7aP5q5ojDCL-DmX_SeniorCoordinator_Curations_KanishkPunjabi.jpg?auto=format,compress,
      },
      {
        id: "cu9",
        name: "Parth Gupta",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/Ns09xWdaLg7F11YM_SeniorCoordinator_Curations_ParthGupta.png?auto=format,compress,
      },
      {
        id: "cu10",
        name: "Parth Santosh Bharati",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/PaI0kLmNmkTH0rOx_JointHead_Curations_ParthBharati.png?auto=format,compress,
      },
      {
        id: "cu11",
        name: "Alisha Chaudhary",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/BqbH1RMFifdCvhaX_Seniorcoordinator_promotions_Alisha.heif?auto=format,compress,
      },
      {
        id: "cu12",
        name: "Nehal Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu13",
        name: "Saurish Mishra",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu14",
        name: "Aarav Goyal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu15",
        name: "Athana Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu16",
        name: "Ayush Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu17",
        name: "Shivansh Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cu18",
        name: "Tanishka",
        role: "Team Member",
        photo: null,
      },

    ],
  },

  // ── Social Media Team ──────────────────────────────────────────────────────
  {
    id: "social-media",
    label: "Social Media Team",
    members: [
      {
        id: "sm1",
        name: "Aarohee Bharadwaj",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "sm2",
        name: "Adrit Das",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm3",
        name: "Gunjita Saxena",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm4",
        name: "Naisha Mangla",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm5",
        name: "Saanvi Lepcha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm6",
        name: "Ankit Sharma",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/T2_uqnYjWDGuhGq7_SeniorCoordinator_SM_AnkitSharma.webp?auto=format,compress,
      },
      {
        id: "sm7",
        name: "Mohd Talha Sufyan",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/0Q3Gf_URNPjxkRb6_0523fc4d04b0fbc33afc1ecb740c4b48dd85d1e7-2304x4096.avif?auto=format,compress,
      },
      {
        id: "sm8",
        name: "Nileshwari Patil",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/7VQ7TU56w0xSLp5w_JointHead_SocialMedia_NileshwariPatil.jpg?auto=format,compress,
      },
      {
        id: "sm9",
        name: "Snehreet Kaur",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/MKanEFJMdUWKTcnb_SeniorCoordinator_Media%26Coverage_SnehreetKaur.jpg?auto=format,compress,
      },
      {
        id: "sm10",
        name: "Srishti Mehta",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/jFp9frvCRhgakPKP_SeniorCoordinator_CommunityRelations_SrishtiMehta.jpeg?auto=format,compress,
      },
      {
        id: "sm11",
        name: "Suhana Verma",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/bTAXa9LBPn5g8ffs_HEAD_SOCIALMEDIA_SUHANAVERMA.jpeg?auto=format,compress,
      },
      {
        id: "sm12",
        name: "Anika Gujral",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm13",
        name: "Divya Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm14",
        name: "Gaadha Amal Nair",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm15",
        name: "Ananya Khanna",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/O_vYMmFAN7BBcpD7_ANANYAKHANNA.jpg?auto=format,compress,
      },
      {
        id: "sm16",
        name: "Ketan Kumar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "sm17",
        name: "Ruchit Kumar Jha",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/ctsQXLRycHBCAqJj_RUCHIT.png?auto=format,compress,
      },
      {
        id: "sm18",
        name: "Aanya Bharadwaj",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Media & Coverage Team ──────────────────────────────────────────────────
  {
    id: "media",
    label: "Media & Coverage Team",
    members: [
      {
        id: "mc1",
        name: "Aditya Raj",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "mc2",
        name: "Dwijesh Chilukuri",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc3",
        name: "Prakhar Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc4",
        name: "Riya Bisht",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc5",
        name: "Hridey Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc6",
        name: "Prakhar Bansal",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/XBMuiisJe2EeYxOQ_SeniorCoordinator_Media%26Coverage_Prakhar.png?auto=format,compress,
      },
      {
        id: "mc7",
        name: "Sanya Varre",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/O7hEGvMmn9KlD_Xx_SanyavarreJointheadmedia%26coverage.JPG?auto=format,compress,
      },
      {
        id: "mc8",
        name: "Tamanna",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc9",
        name: "Tanishka Panda",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc10",
        name: "Yashika Agarwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc11",
        name: "Yashu Pandey",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc12",
        name: "Shivi Srivastava",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc13",
        name: "Shubham Doshi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc14",
        name: "Sugandh Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mc15",
        name: "Tirth patel",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Logistics Team ─────────────────────────────────────────────────────────
  {
    id: "logistics",
    label: "Logistics Team",
    members: [
      {
        id: "lo1",
        name: "Bhavya Chavan",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "lo2",
        name: "Daksh Anand",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo3",
        name: "Shreet Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo4",
        name: "Taran Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo5",
        name: "Mohit Raj",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo6",
        name: "Pranjal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo7",
        name: "Ashish Nath Jha",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/KuZach94L_blszOF_JointHead_CommunityRelations_AshishNathJha.jpeg?auto=format,compress,
      },
      {
        id: "lo8",
        name: "Avadhanula Pranav",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/OQbJY2qwKc9QnkTW_SeniorCoordinator_Programs_PranavAvadhanula.jpeg?auto=format,compress,
      },
      {
        id: "lo9",
        name: "Harshish Kanoi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo10",
        name: "Lakshya",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/Zc3UwuRnR8bDrgaL_Senior_Coordinator_Editorial_Lakshya.jpeg?auto=format,compress,
      },
      {
        id: "lo11",
        name: "Mitul Arora",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/sbHVxkW9CBCNNtke_SeniorCoordinator_Logistics_Mitul.png?auto=format,compress,
      },
      {
        id: "lo12",
        name: "Saksham Joshi",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/VjnAmeuTilURBQyk_JointHead_Logistics_SakshamJoshi.jpg?auto=format,compress,
      },
      {
        id: "lo13",
        name: "Shaurya Pathak",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/VqibI9VcMvO83mb6_Senior_Coordinator_Logistics_Shaurya_Pathak.jpg?auto=format,compress,
      },
      {
        id: "lo14",
        name: "Vishwesh Gaidhani",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/GzQs_UxwgxjrQ8oa_Head_logistics_VishweshGaidhani.HEIC?auto=format,compress,
      },
      {
        id: "lo15",
        name: "Yuvraj Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo16",
        name: "Arpit Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo17",
        name: "Atharv Garg",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo18",
        name: "Daksh Saxena",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo19",
        name: "Jayaditya De",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo20",
        name: "Keshav Bhatia",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo21",
        name: "Mehul Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo22",
        name: "Padhdar M. Mukeshbhai",
        role: "Team Member",
        photo: null,
      },
      {
        id: "lo23",
        name: "Saksham Verma",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Events Team ───────────────────────────────────────────────────────────
  {
    id: "events",
    label: "Events Team",
    members: [
      {
        id: "ev1",
        name: "Aarav Khurana",
        role: "Team Member",
        photo: null,
        linkedin: "",
        github: "",
      },
      {
        id: "ev2",
        name: "Abir Harne",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "ev3",
        name: "Aditi Rai",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev4",
        name: "Amisha Upadhyay",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev5",
        name: "Ananya Mishra",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev6",
        name: "Anukriti Verma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev7",
        name: "Harshvardhan Khaitan",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev8",
        name: "Krishna Kakkar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev9",
        name: "Pari Ahuja",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev10",
        name: "Prisha Mittal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev11",
        name: "Shreyansh Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev12",
        name: "Shriya Raizada",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev13",
        name: "Agrim Tripathi",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/9PoWRzzOYOUAYqVX_SENIORCOORDINATOR_PROMOTIONS_AGRIMTRIPATHI.png?auto=format,compress,
      },
      {
        id: "ev14",
        name: "Aryan Wondraw",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/J9Huqy7Ak6Yr7EGF_JointHead_Corporate_AryanWondraw.jpg?auto=format,compress,
      },
      {
        id: "ev15",
        name: "Kyna Sehgal",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/Maq3dVGVWuCccPlu_SeniorCoordinator_CommunityRelations_KynaSehgal.jpg?auto=format,compress,
      },
      {
        id: "ev16",
        name: "Gargi Singh",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/xIvBy8AkC4WPxpp9_Seniorcoordinator_Programs_GargiSingh.HEIC?auto=format,compress,
      },
      {
        id: "ev17",
        name: "Nishika Jain",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/RyUpkP9G-9Nq0Ati_JointHead_Promotions_NishikaJain.jpg?auto=format,compress,
      },
      {
        id: "ev18",
        name: "Pradyumna Raj Chaudhary",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/pML4zaaf6mt35jXA_SeniorCoordinator_CommunityRelations_PradyumnaRajChaudhary_.jpg?auto=format,compress,
      },
      {
        id: "ev19",
        name: "Mehek Marwaha",
        role: "Team Member",
        photo: https://ieeemuj.cdn.prismic.io/ieeemuj/dRtvNI0jAkj0CYxq_SeniorCoordinator_Community%26Relations_MehekMarwaha.pdf,
      },
      {
        id: "ev20",
        name: "Mohisha Sharma",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/Lpt89Y5Kp_LXNoIc_Head_Programs_MohishaSharma.jpg?auto=format,compress,
      },
      {
        id: "ev21",
        name: "Nandini Bali",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/Uj7qKQBAtu8-IwB2_Seniorcoordinator_Programs_NandiniBali.jpg?auto=format,compress,
      },
      {
        id: "ev22",
        name: "Sahaj Bhattia",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/q4MJL6gibMfAZffG_JointHead_Programs_SahajBhatia.HEIC?auto=format,compress,
      },
      {
        id: "ev23",
        name: "Aditi Agarwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev24",
        name: "Akshita Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev25",
        name: "Ananya Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev26",
        name: "Krishna Tripathi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev27",
        name: "Mahi Mehrotra",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev28",
        name: "Manya Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev29",
        name: "Niharika Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev30",
        name: "Aparna Anand",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev31",
        name: "Daksh Agarwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev32",
        name: "Prannoy Sen",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev33",
        name: "Shreyansh Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev34",
        name: "Sounarda Mondal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev35",
        name: "Swastika Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev36",
        name: "Tia Anuja",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev37",
        name: "Yash Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ev38",
        name: "Yuvraj Sethi",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Marketing Team ────────────────────────────────────────────────────────
  {
    id: "marketing",
    label: "Marketing Team",
    members: [
      {
        id: "mk1",
        name: "Anvi Goyal",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "mk2",
        name: "Daksh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk3",
        name: "Dhruv Talwar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk4",
        name: "Eva Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk5",
        name: "Kashvi Mohta",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "mk6",
        name: "Shresht Gulati",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk7",
        name: "Srishti Suman Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk8",
        name: "Yuvika Sachdeva",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk9",
        name: "Adit Tandon",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/vdVSVNYBidVVGd_1_Seniorcoordinator_promotions_AditTandon.dng?auto=format,compress,
      },
      {
        id: "mk10",
        name: "Akshadha Gupta",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/RnV1mM-AXknYmmGg_JOINTHEAD_CREATIVEASSETS_AKSHADHAGUPTA.jpg?auto=format,compress,
      },
      {
        id: "mk11",
        name: "Alisha Yadav",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/BqbH1RMFifdCvhaX_Seniorcoordinator_promotions_Alisha.heif?auto=format,compress,
      },
      {
        id: "mk12",
        name: "Anshul Pandey",
        role: "Team Member",
        photo: https://images.prismic.io/ieeemuj/s5ZE1iicf_IyrH0M_SeniorCoordinator_CreativeAssetsandInventory_AnshulPandey.jpg?auto=format,compress,
      },
      {
        id: "mk13",
        name: "Arnav Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk14",
        name: "Shriya Stuti",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk15",
        name: "Shriya Stutt",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk16",
        name: "Trishala Ojha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk17",
        name: "Abhigyan Padhy",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk18",
        name: "Abhishek Vishnoi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk19",
        name: "Prarthana Agarwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk20",
        name: "Shouryam Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk21",
        name: "Tanisha Salian",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk22",
        name: "Akansha Banerjee",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk23",
        name: "Arnav Meher",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk24",
        name: "Diwansh Khowala",
        role: "Team Member",
        photo: null,
      },
      {
        id: "mk25",
        name: "Priyanshu",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Corporate Team ────────────────────────────────────────────────────────
  {
    id: "corporate",
    label: "Corporate Team",
    members: [
      {
        id: "cp1",
        name: "Armaan Kashyap",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "cp2",
        name: "Daksh Narwaria",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp3",
        name: "Divya Surve",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp4",
        name: "Krish Barnwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp5",
        name: "Shana Srivastava",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp6",
        name: "Sweera Anand",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp7",
        name: "Amishi kingrani",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp8",
        name: "Atharva Awasthy",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp9",
        name: "Danish Mandalapu",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp10",
        name: "Harsh Wardhan",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp11",
        name: "Manasvi Karthik",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp12",
        name: "Neeyati Agrawal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp13",
        name: "Srisha Jha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp14",
        name: "Aanya Singhal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp15",
        name: "Saisha Narang",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp16",
        name: "Vaibhav Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp17",
        name: "Yash Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp18",
        name: "Akshita Rohilla",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp19",
        name: "Daksh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp20",
        name: "Jivaansh Chandna",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp21",
        name: "Shobham S. Panigarhy",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cp22",
        name: "Vanshika Tyagi",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Hospitality Team ───────────────────────────────────────────────────────
  {
    id: "hospitality",
    label: "Hospitality Team",
    members: [
      {
        id: "ho1",
        name: "Arnav Khanna",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "ho2",
        name: "Chaitanya Bharadwaj",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho3",
        name: "Sanat Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho4",
        name: "Saanvi Mittal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho5",
        name: "Anshika Nagar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho6",
        name: "Devangini",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho7",
        name: "Heet Bhatt",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho8",
        name: "Tushi Choudhary",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho9",
        name: "Arnav Asrani",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho10",
        name: "Naman Saini",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho11",
        name: "Ritesh Soni",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho12",
        name: "Aashi Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho13",
        name: "Harsh Deep Ratna",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho14",
        name: "Prachi",
        role: "Team Member",
        photo: null,
      },
      {
        id: "ho15",
        name: "Veerottam K. Kulshrestha",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Content Team ──────────────────────────────────────────────────────────
  {
    id: "content",
    label: "Content Team",
    members: [
      {
        id: "co1",
        name: "Akshay Pathak",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "co2",
        name: "Devika Beri",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co3",
        name: "Mehr Mehta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co4",
        name: "Rian Anand",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co5",
        name: "Rishita Malik",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co6",
        name: "Geetika Khatri",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co7",
        name: "Ipshita",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co8",
        name: "Lavisna Rohra",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co9",
        name: "Ananya Kedia",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co10",
        name: "Andrea Dia Benjamin",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co11",
        name: "Kavya Das",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co12",
        name: "Akshita Shah",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co13",
        name: "Anushka Soni",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co14",
        name: "Saloni Sinha",
        role: "Team Member",
        photo: null,
      },
      {
        id: "co15",
        name: "Vaibhav Verma",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Finance Team ──────────────────────────────────────────────────────────
  {
    id: "finance",
    label: "Finance Team",
    members: [
      {
        id: "fi1",
        name: "Anshul Sawhney",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "fi2",
        name: "Likisha Grover",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi3",
        name: "Tarush Prasad",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi4",
        name: "Navya Khurana",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi5",
        name: "Riddhi Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi6",
        name: "Suyash K. Kshitij",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi7",
        name: "Dhruv Sahrawat",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi8",
        name: "Jannat Ghuman",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi9",
        name: "Raima",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi10",
        name: "Mansi Thakre",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi11",
        name: "Rachit Goyal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi12",
        name: "Suryansh Thakur",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fi13",
        name: "Tansukh",
        role: "Team Member",
        photo: null,
      },
    ],
  },
    // ── Crafts Team ───────────────────────────────────────────────────────────
  {
    id: "crafts",
    label: "Crafts Team",
    members: [
      {
        id: "cr1",
        name: "Aarushi Gupta",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "cr2",
        name: "Aashie Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr3",
        name: "Akshita Dhiman",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr4",
        name: "Maya Jakhad",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "cr5",
        name: "Radhika Bansal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr6",
        name: "Anhad Ansari",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr7",
        name: "Ayaan Khan",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr8",
        name: "Kashvi Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr9",
        name: "Shubh Vats",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr10",
        name: "Zainab Israr",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr11",
        name: "Ifra Inam",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr12",
        name: "Kiana Agarwal",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr13",
        name: "Spreha Verma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr14",
        name: "Tia Ahuja",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr15",
        name: "Ansh Gupta",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr16",
        name: "Pratik Kaduskar",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr17",
        name: "Priyanshi Garg",
        role: "Team Member",
        photo: null,
      },
      {
        id: "cr18",
        name: "Vritika Trivedi",
        role: "Team Member",
        photo: null,
      },
    ],
  },

  // ── Flying Squad ──────────────────────────────────────────────────────────
  {
    id: "flying-squad",
    label: "Flying Squad",
    members: [
      {
        id: "fs1",
        name: "Anirudh Rawat",
        role: "Team Member",
        photo: null,
        linkedin: "",
      },
      {
        id: "fs2",
        name: "Swapnil Srivastava",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs3",
        name: "Garv Sharma",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs4",
        name: "Rithik Masand",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs5",
        name: "Armon Bhuyan",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs6",
        name: "Arnav Yadav",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs7",
        name: "Sarthak Sahay",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs8",
        name: "Akshit Katare",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs9",
        name: "Devang Garg",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs10",
        name: "Prakhar Singh",
        role: "Team Member",
        photo: null,
      },
      {
        id: "fs11",
        name: "Medhansh",
        role: "Team Member",
        photo: null,
      },

    ],
  },
];
